Repository UMC-TEAM-RF/RF-Server, pull requests merged in 2023-11, with the labels that each got.

#142 브랜치에 커밋시 빌드가 가능한지 확인하는 자동화 생성
  .github/workflows/TestBuild.yml
Labels: ⚙️ 세팅

#143 Feature/#137/major
  src/main/java/org/rf/rfserver/constant/Major.java
  src/main/java/org/rf/rfserver/constant/service/ApiService.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#150 유저별 일정 조회 파라미터 포맷 수정
  src/main/java/org/rf/rfserver/schedule/controller/ScheduleController.java
  src/main/java/org/rf/rfserver/schedule/service/ScheduleService.java
Labels: 🛠️ 구현 개선, ⚔️ 수정

#155 src/resources 의 application.yml 을 ignore되도록 설정
  .gitignore
  src/main/resources/application.yml
Labels: 📝 문서, ⚙️ 세팅
