Repository UMC-TEAM-RF/RF-Server, pull requests merged in 2023-08, with the labels that each got.

#36 채팅 구현
  build.gradle
  src/main/java/org/rf/rfserver/chat/MessageType.java
  src/main/java/org/rf/rfserver/chat/controller/ChatController.java
  src/main/java/org/rf/rfserver/chat/dto/ChatReq.java
  src/main/java/org/rf/rfserver/chat/dto/ChatRes.java
  src/main/java/org/rf/rfserver/chat/repository/ChatRepository.java
  src/main/java/org/rf/rfserver/chat/service/ChatPublisher.java
  src/main/java/org/rf/rfserver/chat/service/ChatSubscriber.java
  src/main/java/org/rf/rfserver/config/WebSocketConfig.java
  src/main/java/org/rf/rfserver/config/redis/RedisConfig.java
  src/main/java/org/rf/rfserver/domain/Chat.java
  src/main/java/org/rf/rfserver/domain/ChattingRoom.java
  src/main/java/org/rf/rfserver/domain/FavoriteChat.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/UserChatting.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
Labels: 🛠️ 구현 개선

#38 Feature/#37/IDnNicknameCheck
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/dto/GetNicknameCheckRes.java
  src/main/java/org/rf/rfserver/user/dto/GetUserIdCheckRes.java
  src/main/java/org/rf/rfserver/user/repository/UserRepository.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#46 Feature/#19/chatting
  src/main/java/org/rf/rfserver/chat/service/ChatSubscriber.java
Labels: 🛠️ 구현 개선

#48 Feature/#47/fixPartyImageUrl
  src/main/java/org/rf/rfserver/config/s3/S3Uploader.java
  src/main/java/org/rf/rfserver/config/s3/TestController.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/party/PartyController.java
  src/main/java/org/rf/rfserver/party/PartyService.java
  src/main/java/org/rf/rfserver/party/dto/PostPartyReq.java
Labels: 🛠️ 구현 개선, 🏗️ 리팩토링

#49 엔티티 정리 및 Enum 클래스 전환
  src/main/java/org/rf/rfserver/constant/Controller/ApiController.java
  src/main/java/org/rf/rfserver/constant/Country.java
  src/main/java/org/rf/rfserver/constant/EnumModel.java
  src/main/java/org/rf/rfserver/constant/Interest.java
  src/main/java/org/rf/rfserver/constant/Language.java
  src/main/java/org/rf/rfserver/constant/LifeStyle.java
  src/main/java/org/rf/rfserver/constant/Mbti.java
  src/main/java/org/rf/rfserver/constant/PreferAges.java
  src/main/java/org/rf/rfserver/constant/Rule.java
  src/main/java/org/rf/rfserver/constant/University.java
  src/main/java/org/rf/rfserver/constant/UniversityUrl.java
  src/main/java/org/rf/rfserver/constant/dto/EnumValue.java
  src/main/java/org/rf/rfserver/constant/service/ApiService.java
  src/main/java/org/rf/rfserver/domain/Country.java
  src/main/java/org/rf/rfserver/domain/Interest.java
  src/main/java/org/rf/rfserver/domain/InterestCategory.java
  src/main/java/org/rf/rfserver/domain/InterestCountry.java
  src/main/java/org/rf/rfserver/domain/Mail.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/PartyInterest.java
  src/main/java/org/rf/rfserver/domain/PartyRule.java
  src/main/java/org/rf/rfserver/domain/PartyTag.java
  src/main/java/org/rf/rfserver/domain/Post.java
  src/main/java/org/rf/rfserver/domain/PostImage.java
  src/main/java/org/rf/rfserver/domain/Rule.java
  src/main/java/org/rf/rfserver/domain/Tag.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/domain/UserInterest.java
  src/main/java/org/rf/rfserver/mail/dto/PostSendReq.java
  src/main/java/org/rf/rfserver/mail/service/MailService.java
  src/main/java/org/rf/rfserver/party/PartyInterestRepository.java
  src/main/java/org/rf/rfserver/party/PartyService.java
  src/main/java/org/rf/rfserver/party/dto/GetPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/PostPartyReq.java
  src/main/java/org/rf/rfserver/user/dto/GetUserRes.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🏗️ 리팩토링

#51 EnableJpaAuditing 어노테이션 추가 및 BaseEntity 생성
  src/main/java/org/rf/rfserver/RfserverApplication.java
  src/main/java/org/rf/rfserver/domain/BaseEntity.java
  src/main/java/org/rf/rfserver/domain/Chat.java
  src/main/java/org/rf/rfserver/domain/FavoriteChat.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/Post.java
  src/main/java/org/rf/rfserver/domain/Report.java
  src/main/java/org/rf/rfserver/domain/Schedule.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/domain/UserParty.java
  src/main/java/org/rf/rfserver/party/PartyService.java
Labels: ⚙️ 세팅, 🏗️ 리팩토링

#61 feature: [#60] mail 전송과 관련된 응답 형태 변경 및 code 삭제
  src/main/java/org/rf/rfserver/mail/dto/PostSendRes.java
  src/main/java/org/rf/rfserver/mail/service/MailService.java
Labels: 🏗️ 리팩토링

#39 Feature/#35/block
  src/main/java/org/rf/rfserver/blockParty/controller/BlockPartyController.java
  src/main/java/org/rf/rfserver/blockParty/dto/BlockPartyRes.java
  src/main/java/org/rf/rfserver/blockParty/repository/BlockPartyRepository.java
  src/main/java/org/rf/rfserver/blockParty/service/BlockPartyService.java
  src/main/java/org/rf/rfserver/blockUser/controller/BlockUserController.java
  src/main/java/org/rf/rfserver/blockUser/dto/DeleteBlockUserRes.java
  src/main/java/org/rf/rfserver/blockUser/dto/GetBlockUserRes.java
  src/main/java/org/rf/rfserver/blockUser/dto/PostBlockUserReq.java
  src/main/java/org/rf/rfserver/blockUser/dto/PostBlockUserRes.java
  src/main/java/org/rf/rfserver/blockUser/repository/BlockUserRepository.java
  src/main/java/org/rf/rfserver/blockUser/service/BlockUserService.java
  src/main/java/org/rf/rfserver/chat/service/ChatPublisher.java
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/domain/BlockParty.java
  src/main/java/org/rf/rfserver/domain/BlockUser.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/Schedule.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/domain/UserParty.java
  src/main/java/org/rf/rfserver/party/PartyController.java
  src/main/java/org/rf/rfserver/party/PartyRepository.java
  src/main/java/org/rf/rfserver/party/PartyService.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/JoinPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/JoinPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/LeavePartyRes.java
  src/main/java/org/rf/rfserver/party/dto/UserCreatePartyReq.java
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
  src/main/java/org/rf/rfserver/party/repository/UserPartyRepository.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
  src/main/java/org/rf/rfserver/report/service/ReportService.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
  src/main/resources/application.yml
Labels: 🛠️ 구현 개선

#43 Feature/#29/group join
  build.gradle
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/constant/RfRule.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/PartyJoinApplication.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/domain/UserParty.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/PostPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/DeletePartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/GetPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/partyjoin/PostApproveJoinRes.java
  src/main/java/org/rf/rfserver/party/dto/partyjoin/PostDenyJoinRes.java
  src/main/java/org/rf/rfserver/party/dto/partyjoinapply/PostJoinApplicationReq.java
  src/main/java/org/rf/rfserver/party/dto/partyjoinapply/PostJoinApplicationRes.java
  src/main/java/org/rf/rfserver/party/repository/PartyJoinApplicationRepository.java
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
  src/main/java/org/rf/rfserver/party/repository/UserPartyRepository.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
  src/main/java/org/rf/rfserver/user/dto/GetUserProfileRes.java
  src/main/java/org/rf/rfserver/user/repository/UserRepository.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
  src/main/resources/application.yml
Labels: 🛠️ 구현 개선

#69 채팅 신고 API
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/constant/ReportType.java
  src/main/java/org/rf/rfserver/constant/service/ApiService.java
  src/main/java/org/rf/rfserver/domain/Report.java
  src/main/java/org/rf/rfserver/report/controller/ReportController.java
  src/main/java/org/rf/rfserver/report/dto/GetReportActorRes.java
  src/main/java/org/rf/rfserver/report/dto/GetReportReporterRes.java
  src/main/java/org/rf/rfserver/report/dto/GetReportRes.java
  src/main/java/org/rf/rfserver/report/dto/PostReportReq.java
  src/main/java/org/rf/rfserver/report/dto/PostReportRes.java
  src/main/java/org/rf/rfserver/report/repository/ReportRepository.java
  src/main/java/org/rf/rfserver/report/service/ReportService.java
Labels: 🛠️ 구현 개선, 🏗️ 리팩토링

#70 Mail 아이디 찾기 / 비밀번호 재설정
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/constant/MailMessage.java
  src/main/java/org/rf/rfserver/domain/Mail.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/mail/dto/PostResetPasswordReq.java
  src/main/java/org/rf/rfserver/mail/dto/PostResetPasswordRes.java
  src/main/java/org/rf/rfserver/mail/service/MailService.java
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/repository/UserRepository.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#74 fix: [#72] 중복 dto 삭제, return 타입을 userProfiles로 변경
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/JoinPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/JoinPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/UserCreatePartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/LeavePartyRes.java
  src/main/java/org/rf/rfserver/party/dto/partyjoinapply/PostJoinApplicationReq.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: ⚔️ 수정

#80 feature: [#79] 중복 id 가입 방지
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#81 메인 페이지에서 사용자 관심사를 기반으로 한 모임 리스트 조회(추천)
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/party/GetInterestPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyReq.java
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#84 feature: [#82]: 가입 승인 검증 추가
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#89 같은 대학교 내의 모임만 조회 추가
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
Labels: 🛠️ 구현 개선

#77 Feature/#75/recruiting
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/JoinPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/GetPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/TogglePartyRecruitmentRes.java
  src/main/java/org/rf/rfserver/party/dto/partyjoinapply/PostJoinApplicationReq.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#96 User 프로필 이미지 관련 기능 구현
  src/main/java/org/rf/rfserver/config/s3/S3Uploader.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/dto/GetUserRes.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선, 🏗️ 리팩토링

#100 Feature/#99/party update
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/party/GetInterestPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/GetPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/PatchPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/PatchPartyRes.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyRes.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#104 Feature/#103/ejection
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/party/EjectUserReq.java
  src/main/java/org/rf/rfserver/party/dto/party/EjectUserRes.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#98 모임 검색 기능
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#116 hotfix [#115] : userId 필수로 받도록 수정
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
Labels: 🏗️ 리팩토링

#120 hotfix: [#119] : delete Duplication
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
Labels: ⚔️ 수정

#117 푸시 구현
  src/main/java/org/rf/rfserver/apns/controller/ApnsTestController.java
  src/main/java/org/rf/rfserver/apns/dto/PushDto.java
  src/main/java/org/rf/rfserver/apns/service/ApnsService.java
  src/main/java/org/rf/rfserver/apns/service/PushNotificationService.java
  src/main/java/org/rf/rfserver/chat/dto/ChatDto.java
  src/main/java/org/rf/rfserver/chat/repository/ChatRepository.java
  src/main/java/org/rf/rfserver/chat/service/ChatPublisher.java
  src/main/java/org/rf/rfserver/config/AsyncConfig.java
  src/main/java/org/rf/rfserver/domain/Chat.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
  src/main/java/org/rf/rfserver/redisDomain/partyidUserid/PartyidUserid.java
  src/main/java/org/rf/rfserver/redisDomain/partyidUserid/repository/PartyidUseridRepository.java
  src/main/java/org/rf/rfserver/redisDomain/partyidUserid/service/PartyidUseridService.java
Labels: 🛠️ 구현 개선

#113 개인 모임 추천
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/repository/PartyRepository.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#105 모임 랜덤 이미지 지정 기능 구현
  src/main/java/org/rf/rfserver/config/s3/S3Uploader.java
  src/main/java/org/rf/rfserver/config/s3/TestController.java
  src/main/java/org/rf/rfserver/constant/Banner.java
  src/main/java/org/rf/rfserver/party/controller/PartyController.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyReq.java
  src/main/java/org/rf/rfserver/party/dto/party/PostPartyRes.java
  src/main/java/org/rf/rfserver/party/service/PartyService.java
Labels: 🛠️ 구현 개선

#124 Hotfix/#121/security
  src/main/java/org/rf/rfserver/config/WebSecurityConfig.java
Labels: ⚔️ 수정

#123 feature [#118] : 좋아요 누름/취소, 싫어요 누름/취소
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#122 User 생성 시 기본 프로필 이미지 지정
  src/main/java/org/rf/rfserver/party/service/PartyService.java
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: ⚔️ 수정

#126 feat(#125) : 채팅 jwt 우회 설정
  src/main/java/org/rf/rfserver/config/WebSecurityConfig.java
Labels: ⚔️ 수정

#130 fix: [#129] 오타수정
  src/main/java/org/rf/rfserver/constant/Rule.java
Labels: ⚔️ 수정
