Repository UMC-TEAM-RF/RF-Server, pull requests merged in 2023-07, with the labels that each got.

#3 feat(#2): BaseResponse 관련 코드를 생성하였습니다
  src/main/java/org/rf/rfserver/config/BaseException.java
  src/main/java/org/rf/rfserver/config/BaseResponse.java
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
Labels: ⚙️ 세팅, 🛠️ 구현 개선

#4 Feature/#1/entity
  src/main/java/org/rf/rfserver/domain/Chatting.java
  src/main/java/org/rf/rfserver/domain/ChattingRoom.java
  src/main/java/org/rf/rfserver/domain/Country.java
  src/main/java/org/rf/rfserver/domain/FavoriteChatting.java
  src/main/java/org/rf/rfserver/domain/Group.java
  src/main/java/org/rf/rfserver/domain/GroupGroupInterest.java
  src/main/java/org/rf/rfserver/domain/GroupInterest.java
  src/main/java/org/rf/rfserver/domain/GroupRule.java
  src/main/java/org/rf/rfserver/domain/GroupTag.java
  src/main/java/org/rf/rfserver/domain/Interest.java
  src/main/java/org/rf/rfserver/domain/InterestCategory.java
  src/main/java/org/rf/rfserver/domain/InterestCountry.java
  src/main/java/org/rf/rfserver/domain/Post.java
  src/main/java/org/rf/rfserver/domain/PostImage.java
  src/main/java/org/rf/rfserver/domain/Report.java
  src/main/java/org/rf/rfserver/domain/Rule.java
  src/main/java/org/rf/rfserver/domain/Schedule.java
  src/main/java/org/rf/rfserver/domain/Tag.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/domain/UserChatting.java
  src/main/java/org/rf/rfserver/domain/UserGroup.java
  src/main/java/org/rf/rfserver/domain/UserInterest.java
Labels: 🛠️ 구현 개선

#11 hotfix(#7) : 환경 변수를 사용하여 서버와 연결이 가능하게 작성하였습니다.
  src/main/resources/application.yml
Labels: ⚙️ 세팅

#16 hotfix(#15) : build.gradle의 spring security 관련 dependency를 제거했습니다.
  build.gradle
Labels: 📝 문서, ⚙️ 세팅

#18 Feature/#5/user crud
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/user/controller/UserController.java
  src/main/java/org/rf/rfserver/user/dto/DeleteUserRes.java
  src/main/java/org/rf/rfserver/user/dto/GetUserRes.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserReq.java
  src/main/java/org/rf/rfserver/user/dto/PatchUserRes.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
  src/main/java/org/rf/rfserver/user/dto/PostUserRes.java
  src/main/java/org/rf/rfserver/user/repository/UserRepository.java
  src/main/java/org/rf/rfserver/user/service/UserService.java
Labels: 🛠️ 구현 개선

#27 hotfix(#25) : user party 연관 수정
  src/main/java/org/rf/rfserver/domain/Party.java
Labels: 🐛 버그, ⚔️ 수정

#28 Feature/#22/s3 file upload
  build.gradle
  src/main/java/org/rf/rfserver/RfserverApplication.java
  src/main/java/org/rf/rfserver/config/s3/S3Config.java
  src/main/java/org/rf/rfserver/config/s3/S3Uploader.java
  src/main/java/org/rf/rfserver/config/s3/TestController.java
  src/main/resources/application.yml
Labels: 🛠️ 구현 개선

#32 Feature/#9/utils
  appspec.yml
  build.gradle
  src/main/java/org/rf/rfserver/config/BaseResponse.java
  src/main/java/org/rf/rfserver/config/BaseResponseStatus.java
  src/main/java/org/rf/rfserver/domain/Mail.java
  src/main/java/org/rf/rfserver/domain/MailMessage.java
  src/main/java/org/rf/rfserver/domain/MailRegex.java
  src/main/java/org/rf/rfserver/domain/Party.java
  src/main/java/org/rf/rfserver/domain/User.java
  src/main/java/org/rf/rfserver/mail/controller/MailController.java
  src/main/java/org/rf/rfserver/mail/dto/PostCheckReq.java
  src/main/java/org/rf/rfserver/mail/dto/PostCheckRes.java
  src/main/java/org/rf/rfserver/mail/dto/PostSendReq.java
  src/main/java/org/rf/rfserver/mail/dto/PostSendRes.java
  src/main/java/org/rf/rfserver/mail/exception/InvalidMailException.java
  src/main/java/org/rf/rfserver/mail/exception/UnauthorizedException.java
  src/main/java/org/rf/rfserver/mail/service/MailService.java
  src/main/java/org/rf/rfserver/user/dto/PostUserReq.java
  src/main/resources/application.yml
Labels: 🛠️ 구현 개선
